MODELDEF Trans_ETD39_th
{
//+---------------------------------------------------+
//|    PExprt THERMAL MODEL FOR MAGNETIC COMPONENT    |
//|         TWIN BUILDER (R) LANGUAGE VERSION         |
//| GENERATED BY PExprt (TM). © 2022 UPM-SAS IP, Inc. |
//|                  Release 2022 R2                  |
//+---------------------------------------------------+


// --- Input ports ---

PORT real in: Period = Tend;
PORT real in: AvgCoreLosses = AvgCoreLosses;
PORT real in: AvgWireLosses = AvgWireLosses;

// --- Output port ---

PORT real out: TempMax = TempMax.MEAN;

// --- 2D Thermal model description for Twin Builder ---

// --- Winding losses share ---

// --- Winding 1 ---

INTERN EQU {Pwind1:=AvgWireLosses*3177.32/(3177.32+373.959+453.903+533.847);} DST: SIM(Type:=SSGM, Sequ:=PRE);

// --- Winding 2 ---

INTERN EQU {Pwind2:=AvgWireLosses*373.959/(3177.32+373.959+453.903+533.847);} DST: SIM(Type:=SSGM, Sequ:=PRE);

// --- Winding 3 ---

INTERN EQU {Pwind3:=AvgWireLosses*453.903/(3177.32+373.959+453.903+533.847);} DST: SIM(Type:=SSGM, Sequ:=PRE);

// --- Winding 4 ---

INTERN EQU {Pwind4:=AvgWireLosses*533.847/(3177.32+373.959+453.903+533.847);} DST: SIM(Type:=SSGM, Sequ:=PRE);

// --- Magnetic component temperature ---

INTERN EQU {TempMaxNoAvg:=AvgCoreLosses*10.9109+Pwind1*10.0735+Pwind2*10.0749+Pwind3*10.0735+Pwind4*10.0724;} DST: SIM(Type:=SSGM, Sequ:=PRE);
UMODEL MOV_AV TempMax (INPUT:=TempMaxNoAvg, TSTART:=0, TSTOP:=Tend, PERIOD:=Period) SRC: DB(Lib:="Simplorer Elements\Basic Elements\Basic Elements");
}