MODELDEF Trans_ETD39
{
//+---------------------------------------------------+
//|   PExprt FEA BASED MODEL FOR MAGNETIC COMPONENT   |
//|         TWIN BUILDER (R) LANGUAGE VERSION         |
//| GENERATED BY PExprt (TM). © 2022 UPM-SAS IP, Inc. |
//|                  Release 2022 R2                  |
//+---------------------------------------------------+
//|          Frequency Domain Model Version           |
//+---------------------------------------------------+

// --- Model Type: FEA ---

// --- Electrical ports ---

PORT electrical: Ap_center;
PORT electrical: Am_center;
PORT electrical: Bp_center;
PORT electrical: Bm_center;
PORT electrical: Cp_center;
PORT electrical: Cm_center;
PORT electrical: Dp_center;
PORT electrical: Dm_center;

// --- Input port ---

PORT real in: Period = Tend;

// --- Output ports ---

PORT real out: AvgTotalLosses = AvgTotalLosses.MEAN;
PORT real out: AvgCoreLosses = AvgCoreLosses.MEAN;
PORT real out: AvgWireLosses = AvgWireLosses;
PORT real out: TotalLosses = TotalLosses;
PORT real out: CoreLosses = CoreLosses;
PORT real out: WireLosses = WireLosses;

// --- Winding wattmeters ---

INTERN WM  WMsens1  NV1:=Ap_center, NV2:=Am_center, NA1:=Ap_center, NA2:=N1_1  ();
INTERN WM  WMsens2  NV1:=Bp_center, NV2:=Bm_center, NA1:=Bp_center, NA2:=N2_1  ();
INTERN WM  WMsens3  NV1:=Cp_center, NV2:=Cm_center, NA1:=Cp_center, NA2:=N3_1  ();
INTERN WM  WMsens4  NV1:=Dp_center, NV2:=Dm_center, NA1:=Dp_center, NA2:=N4_1  ();

// --- Core wattmeter for winding 1 ---

INTERN WM  WMsensCore1  NV1:=N1_5, NV2:=Am_center, NA1:=N1_5, NA2:=N1_6  ();

INTERN R   R_Eddy1  N1:=N1_6, N2:=Am_center  (R:=300.529796k);

// --- Winding wind_1 ---

INTERN EV  euEMF_wind_1  N1:=N1_6, N2:=ne1_wind_1  (QUANT:=vmAux_wind_1.V, FACT:=2.100000e+01);
INTERN AM  amE_wind_1  N1:=ne1_wind_1, N2:=ne2_wind_1  ();
INTERN R   r_wind_1  N1:=ne2_wind_1, N2:=Am_center  (R:=10n);
INTERN EI  eiMMF_wind_1  N1:=GND, N2:=nm_wind_1  (QUANT:=amE_wind_1.I, FACT:=-(2.100000e+01));
INTERN AM  amM_wind_1  N1:=nm_wind_1, N2:=M2  ();
INTERN II  iiAux_wind_1  N1:=GND, N2:=nm1_wind_1  (QUANT:=amM_wind_1.I, FACT:=1);
INTERN L   lAux_wind_1  N1:=GND, N2:=nm1_wind_1  (L:=1, I0:=0);
INTERN VM  vmAux_wind_1  N1:=nm1_wind_1, N2:=GND  ();

// --- Core wattmeter for winding 2 ---

INTERN WM  WMsensCore2  NV1:=N2_5, NV2:=Bm_center, NA1:=N2_5, NA2:=N2_6  ();

// --- Winding wind_2 ---

INTERN EV  euEMF_wind_2  N1:=N2_6, N2:=ne1_wind_2  (QUANT:=vmAux_wind_2.V, FACT:=3.000000e+00);
INTERN AM  amE_wind_2  N1:=ne1_wind_2, N2:=ne2_wind_2  ();
INTERN R   r_wind_2  N1:=ne2_wind_2, N2:=Bm_center  (R:=10n);
INTERN EI  eiMMF_wind_2  N1:=M2, N2:=nm_wind_2  (QUANT:=amE_wind_2.I, FACT:=-(3.000000e+00));
INTERN AM  amM_wind_2  N1:=nm_wind_2, N2:=M3  ();
INTERN II  iiAux_wind_2  N1:=GND, N2:=nm1_wind_2  (QUANT:=amM_wind_2.I, FACT:=1);
INTERN L   lAux_wind_2  N1:=GND, N2:=nm1_wind_2  (L:=1, I0:=0);
INTERN VM  vmAux_wind_2  N1:=nm1_wind_2, N2:=GND  ();

// --- Core wattmeter for winding 3 ---

INTERN WM  WMsensCore3  NV1:=N3_5, NV2:=Cm_center, NA1:=N3_5, NA2:=N3_6  ();

// --- Winding wind_3 ---

INTERN EV  euEMF_wind_3  N1:=N3_6, N2:=ne1_wind_3  (QUANT:=vmAux_wind_3.V, FACT:=3.000000e+00);
INTERN AM  amE_wind_3  N1:=ne1_wind_3, N2:=ne2_wind_3  ();
INTERN R   r_wind_3  N1:=ne2_wind_3, N2:=Cm_center  (R:=10n);
INTERN EI  eiMMF_wind_3  N1:=M3, N2:=nm_wind_3  (QUANT:=amE_wind_3.I, FACT:=-(3.000000e+00));
INTERN AM  amM_wind_3  N1:=nm_wind_3, N2:=M4  ();
INTERN II  iiAux_wind_3  N1:=GND, N2:=nm1_wind_3  (QUANT:=amM_wind_3.I, FACT:=1);
INTERN L   lAux_wind_3  N1:=GND, N2:=nm1_wind_3  (L:=1, I0:=0);
INTERN VM  vmAux_wind_3  N1:=nm1_wind_3, N2:=GND  ();

// --- Core wattmeter for winding 4 ---

INTERN WM  WMsensCore4  NV1:=N4_5, NV2:=Dm_center, NA1:=N4_5, NA2:=N4_6  ();

// --- Winding wind_4 ---

INTERN EV  euEMF_wind_4  N1:=N4_6, N2:=ne1_wind_4  (QUANT:=vmAux_wind_4.V, FACT:=3.000000e+00);
INTERN AM  amE_wind_4  N1:=ne1_wind_4, N2:=ne2_wind_4  ();
INTERN R   r_wind_4  N1:=ne2_wind_4, N2:=Dm_center  (R:=10n);
INTERN EI  eiMMF_wind_4  N1:=M4, N2:=nm_wind_4  (QUANT:=amE_wind_4.I, FACT:=-(3.000000e+00));
INTERN AM  amM_wind_4  N1:=nm_wind_4, N2:=M5  ();
INTERN II  iiAux_wind_4  N1:=GND, N2:=nm1_wind_4  (QUANT:=amM_wind_4.I, FACT:=1);
INTERN L   lAux_wind_4  N1:=GND, N2:=nm1_wind_4  (L:=1, I0:=0);
INTERN VM  vmAux_wind_4  N1:=nm1_wind_4, N2:=GND  ();

// --- MODEL FOR GAP ---

INTERN R   RMAGLINEAR_GAP  N1:=M5, N2:=Mx  (R:=5.052841meg);

// --- MODEL FOR LINEAR CORE ETD39/20/13 ---

INTERN R   RMAGLINEAR_PExprt_Core  N1:=Mx, N2:=GND  (R:=447.237699k);

// --- Self impedance Z1_1 ---

INTERN R   Rser_1_1_0  N1:=N1_1, N2:=N1_1_0  (R:=12.902006m);
INTERN L   Lser_1_1_0  N1:=N1_1_0, N2:=N1_1_1  (L:=20.693600u, I0:=0);
INTERN R   Rpar_1_1_1  N1:=N1_1_1, N2:=N1_1_2  (R:=1.612663);
INTERN L   Lpar_1_1_1  N1:=N1_1_1, N2:=N1_1_2  (L:=57.009566n, I0:=0);
INTERN R   Rpar_1_1_2  N1:=N1_1_2, N2:=N1_1_3  (R:=26.322232);
INTERN L   Lpar_1_1_2  N1:=N1_1_2, N2:=N1_1_3  (L:=23.346919n, I0:=0);
INTERN R   Rpar_1_1_3  N1:=N1_1_3, N2:=N1_2  (R:=34.732286);
INTERN L   Lpar_1_1_3  N1:=N1_1_3, N2:=N1_2  (L:=136.918876n, I0:=0);

// --- Mutual impedance Z1_2 --- 

INTERN I   IIsens_1_2  N1:=GND, N2:=z_1_2  (IS:=WMsens2.I, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=WMsens2.I);
INTERN VM  VMZ_1_2  N1:=z_1_2, N2:=GND  ();
INTERN E   EUdrop_1_2  N1:=N1_3, N2:=N1_2  (EMF:=VMZ_1_2.V, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=VMZ_1_2.V);
INTERN R   Rser_1_2_0  N1:=z_1_2, N2:=N1_2_0  (R:=-86.072152u);
INTERN L   Lser_1_2_0  N1:=N1_2_0, N2:=N1_2_1  (L:=1.803384u, I0:=0);
INTERN R   Rpar_1_2_1  N1:=N1_2_1, N2:=N1_2_2  (R:=-1.025267m);
INTERN L   Lpar_1_2_1  N1:=N1_2_1, N2:=N1_2_2  (L:=-33.273126p, I0:=0);
INTERN R   Rpar_1_2_2  N1:=N1_2_2, N2:=N1_2_3  (R:=-140.377774m);
INTERN L   Lpar_1_2_2  N1:=N1_2_2, N2:=N1_2_3  (L:=-14.190449n, I0:=0);
INTERN R   Rpar_1_2_3  N1:=N1_2_3, N2:=N1_2_4  (R:=-7.070199m);
INTERN L   Lpar_1_2_3  N1:=N1_2_3, N2:=N1_2_4  (L:=-2.060365n, I0:=0);
INTERN R   Rpar_1_2_4  N1:=N1_2_4, N2:=N1_2_5  (R:=115.190196m);
INTERN L   Lpar_1_2_4  N1:=N1_2_4, N2:=N1_2_5  (L:=4.072112n, I0:=0);
INTERN R   Rpar_1_2_5  N1:=N1_2_5, N2:=N1_2_6  (R:=1.880159);
INTERN L   Lpar_1_2_5  N1:=N1_2_5, N2:=N1_2_6  (L:=1.667637n, I0:=0);
INTERN R   Rpar_1_2_6  N1:=N1_2_6, N2:=N1_2_7  (R:=2.480878);
INTERN L   Lpar_1_2_6  N1:=N1_2_6, N2:=N1_2_7  (L:=9.779920n, I0:=0);
INTERN R   Rpar_1_2_7  N1:=N1_2_7, N2:=N1_2_8  (R:=2.447837k);
INTERN L   Lpar_1_2_7  N1:=N1_2_7, N2:=N1_2_8  (L:=622.692167n, I0:=0);
INTERN R   Rpar_1_2_8  N1:=N1_2_8, N2:=N1_2_9  (R:=2.156185);
INTERN L   Lpar_1_2_8  N1:=N1_2_8, N2:=N1_2_9  (L:=8.115927n, I0:=0);
INTERN R   Rpar_1_2_9  N1:=N1_2_9, N2:=GND  (R:=28.148189);
INTERN L   Lpar_1_2_9  N1:=N1_2_9, N2:=GND  (L:=150.429164n, I0:=0);

// --- Mutual impedance Z1_3 --- 

INTERN I   IIsens_1_3  N1:=GND, N2:=z_1_3  (IS:=WMsens3.I, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=WMsens3.I);
INTERN VM  VMZ_1_3  N1:=z_1_3, N2:=GND  ();
INTERN E   EUdrop_1_3  N1:=N1_4, N2:=N1_3  (EMF:=VMZ_1_3.V, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=VMZ_1_3.V);
INTERN R   Rser_1_3_0  N1:=z_1_3, N2:=N1_3_0  (R:=-212.495611u);
INTERN L   Lser_1_3_0  N1:=N1_3_0, N2:=N1_3_1  (L:=2.595732u, I0:=0);
INTERN R   Rpar_1_3_1  N1:=N1_3_1, N2:=N1_3_2  (R:=-331.448223m);
INTERN L   Lpar_1_3_1  N1:=N1_3_1, N2:=N1_3_2  (L:=-20.291063n, I0:=0);
INTERN R   Rpar_1_3_2  N1:=N1_3_2, N2:=N1_3_3  (R:=-12.996233m);
INTERN L   Lpar_1_3_2  N1:=N1_3_2, N2:=N1_3_3  (L:=-284.119241p, I0:=0);
INTERN R   Rpar_1_3_3  N1:=N1_3_3, N2:=N1_3_4  (R:=-62.804764m);
INTERN L   Lpar_1_3_3  N1:=N1_3_3, N2:=N1_3_4  (L:=-5.091500n, I0:=0);
INTERN R   Rpar_1_3_4  N1:=N1_3_4, N2:=N1_3_5  (R:=115.190196m);
INTERN L   Lpar_1_3_4  N1:=N1_3_4, N2:=N1_3_5  (L:=4.072112n, I0:=0);
INTERN R   Rpar_1_3_5  N1:=N1_3_5, N2:=N1_3_6  (R:=1.880159);
INTERN L   Lpar_1_3_5  N1:=N1_3_5, N2:=N1_3_6  (L:=1.667637n, I0:=0);
INTERN R   Rpar_1_3_6  N1:=N1_3_6, N2:=N1_3_7  (R:=2.480878);
INTERN L   Lpar_1_3_6  N1:=N1_3_6, N2:=N1_3_7  (L:=9.779920n, I0:=0);
INTERN R   Rpar_1_3_7  N1:=N1_3_7, N2:=N1_3_8  (R:=606.945790m);
INTERN L   Lpar_1_3_7  N1:=N1_3_7, N2:=N1_3_8  (L:=4.508442n, I0:=0);
INTERN R   Rpar_1_3_8  N1:=N1_3_8, N2:=N1_3_9  (R:=130.194294m);
INTERN L   Lpar_1_3_8  N1:=N1_3_8, N2:=N1_3_9  (L:=180.798014p, I0:=0);
INTERN R   Rpar_1_3_9  N1:=N1_3_9, N2:=GND  (R:=1.767108);
INTERN L   Lpar_1_3_9  N1:=N1_3_9, N2:=GND  (L:=46.815855n, I0:=0);

// --- Mutual impedance Z1_4 --- 

INTERN I   IIsens_1_4  N1:=GND, N2:=z_1_4  (IS:=WMsens4.I, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=WMsens4.I);
INTERN VM  VMZ_1_4  N1:=z_1_4, N2:=GND  ();
INTERN E   EUdrop_1_4  N1:=N1_5, N2:=N1_4  (EMF:=VMZ_1_4.V, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=VMZ_1_4.V);
INTERN R   Rser_1_4_0  N1:=z_1_4, N2:=N1_4_0  (R:=658.998715u);
INTERN L   Lser_1_4_0  N1:=N1_4_0, N2:=N1_4_1  (L:=2.534001u, I0:=0);
INTERN R   Rpar_1_4_1  N1:=N1_4_1, N2:=N1_4_2  (R:=-5.794223m);
INTERN L   Lpar_1_4_1  N1:=N1_4_1, N2:=N1_4_2  (L:=-65.247742p, I0:=0);
INTERN R   Rpar_1_4_2  N1:=N1_4_2, N2:=N1_4_3  (R:=-110.826770m);
INTERN L   Lpar_1_4_2  N1:=N1_4_2, N2:=N1_4_3  (L:=-19.280251n, I0:=0);
INTERN R   Rpar_1_4_3  N1:=N1_4_3, N2:=N1_4_4  (R:=-2.470226m);
INTERN L   Lpar_1_4_3  N1:=N1_4_3, N2:=N1_4_4  (L:=-1.072309p, I0:=0);
INTERN R   Rpar_1_4_4  N1:=N1_4_4, N2:=N1_4_5  (R:=115.190196m);
INTERN L   Lpar_1_4_4  N1:=N1_4_4, N2:=N1_4_5  (L:=4.072112n, I0:=0);
INTERN R   Rpar_1_4_5  N1:=N1_4_5, N2:=N1_4_6  (R:=1.880159);
INTERN L   Lpar_1_4_5  N1:=N1_4_5, N2:=N1_4_6  (L:=1.667637n, I0:=0);
INTERN R   Rpar_1_4_6  N1:=N1_4_6, N2:=N1_4_7  (R:=2.480878);
INTERN L   Lpar_1_4_6  N1:=N1_4_6, N2:=N1_4_7  (L:=9.779920n, I0:=0);
INTERN R   Rpar_1_4_7  N1:=N1_4_7, N2:=N1_4_8  (R:=128.779306m);
INTERN L   Lpar_1_4_7  N1:=N1_4_7, N2:=N1_4_8  (L:=5.136723n, I0:=0);
INTERN R   Rpar_1_4_8  N1:=N1_4_8, N2:=N1_4_9  (R:=12.383141);
INTERN L   Lpar_1_4_8  N1:=N1_4_8, N2:=N1_4_9  (L:=46.972273n, I0:=0);
INTERN R   Rpar_1_4_9  N1:=N1_4_9, N2:=GND  (R:=8.026437);
INTERN L   Lpar_1_4_9  N1:=N1_4_9, N2:=GND  (L:=87.893690n, I0:=0);

// --- Mutual impedance Z2_1 --- 

INTERN I   IIsens_2_1  N1:=GND, N2:=z_2_1  (IS:=WMsens1.I, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=WMsens1.I);
INTERN VM  VMZ_2_1  N1:=z_2_1, N2:=GND  ();
INTERN E   EUdrop_2_1  N1:=N2_2, N2:=N2_1  (EMF:=VMZ_2_1.V, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=VMZ_2_1.V);
INTERN R   Rser_2_1_0  N1:=z_2_1, N2:=N2_1_0  (R:=-86.072152u);
INTERN L   Lser_2_1_0  N1:=N2_1_0, N2:=N2_1_1  (L:=1.803384u, I0:=0);
INTERN R   Rpar_2_1_1  N1:=N2_1_1, N2:=N2_1_2  (R:=-1.025267m);
INTERN L   Lpar_2_1_1  N1:=N2_1_1, N2:=N2_1_2  (L:=-33.273126p, I0:=0);
INTERN R   Rpar_2_1_2  N1:=N2_1_2, N2:=N2_1_3  (R:=-140.377774m);
INTERN L   Lpar_2_1_2  N1:=N2_1_2, N2:=N2_1_3  (L:=-14.190449n, I0:=0);
INTERN R   Rpar_2_1_3  N1:=N2_1_3, N2:=N2_1_4  (R:=-7.070199m);
INTERN L   Lpar_2_1_3  N1:=N2_1_3, N2:=N2_1_4  (L:=-2.060365n, I0:=0);
INTERN R   Rpar_2_1_4  N1:=N2_1_4, N2:=N2_1_5  (R:=115.190196m);
INTERN L   Lpar_2_1_4  N1:=N2_1_4, N2:=N2_1_5  (L:=4.072112n, I0:=0);
INTERN R   Rpar_2_1_5  N1:=N2_1_5, N2:=N2_1_6  (R:=1.880159);
INTERN L   Lpar_2_1_5  N1:=N2_1_5, N2:=N2_1_6  (L:=1.667637n, I0:=0);
INTERN R   Rpar_2_1_6  N1:=N2_1_6, N2:=N2_1_7  (R:=2.480878);
INTERN L   Lpar_2_1_6  N1:=N2_1_6, N2:=N2_1_7  (L:=9.779920n, I0:=0);
INTERN R   Rpar_2_1_7  N1:=N2_1_7, N2:=N2_1_8  (R:=2.447837k);
INTERN L   Lpar_2_1_7  N1:=N2_1_7, N2:=N2_1_8  (L:=622.692167n, I0:=0);
INTERN R   Rpar_2_1_8  N1:=N2_1_8, N2:=N2_1_9  (R:=2.156185);
INTERN L   Lpar_2_1_8  N1:=N2_1_8, N2:=N2_1_9  (L:=8.115927n, I0:=0);
INTERN R   Rpar_2_1_9  N1:=N2_1_9, N2:=GND  (R:=28.148189);
INTERN L   Lpar_2_1_9  N1:=N2_1_9, N2:=GND  (L:=150.429164n, I0:=0);

// --- Self impedance Z2_2 ---

INTERN R   Rser_2_2_0  N1:=N2_2, N2:=N2_2_0  (R:=1.547220m);
INTERN L   Lser_2_2_0  N1:=N2_2_0, N2:=N2_2_1  (L:=706.197679n, I0:=0);
INTERN R   Rpar_2_2_1  N1:=N2_2_1, N2:=N2_2_2  (R:=699.382041);
INTERN L   Lpar_2_2_1  N1:=N2_2_1, N2:=N2_2_2  (L:=177.912048n, I0:=0);
INTERN R   Rpar_2_2_2  N1:=N2_2_2, N2:=N2_2_3  (R:=616.052807m);
INTERN L   Lpar_2_2_2  N1:=N2_2_2, N2:=N2_2_3  (L:=2.318836n, I0:=0);
INTERN R   Rpar_2_2_3  N1:=N2_2_3, N2:=N2_3  (R:=8.042340);
INTERN L   Lpar_2_2_3  N1:=N2_2_3, N2:=N2_3  (L:=42.979761n, I0:=0);

// --- Mutual impedance Z2_3 --- 

INTERN I   IIsens_2_3  N1:=GND, N2:=z_2_3  (IS:=WMsens3.I, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=WMsens3.I);
INTERN VM  VMZ_2_3  N1:=z_2_3, N2:=GND  ();
INTERN E   EUdrop_2_3  N1:=N2_4, N2:=N2_3  (EMF:=VMZ_2_3.V, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=VMZ_2_3.V);
INTERN R   Rser_2_3_0  N1:=z_2_3, N2:=N2_3_0  (R:=41.868241u);
INTERN L   Lser_2_3_0  N1:=N2_3_0, N2:=N2_3_1  (L:=756.654909n, I0:=0);
INTERN R   Rpar_2_3_1  N1:=N2_3_1, N2:=N2_3_2  (R:=-23.101861m);
INTERN L   Lpar_2_3_1  N1:=N2_3_1, N2:=N2_3_2  (L:=-4.037983n, I0:=0);
INTERN R   Rpar_2_3_2  N1:=N2_3_2, N2:=N2_3_3  (R:=-57.765884u);
INTERN L   Lpar_2_3_2  N1:=N2_3_2, N2:=N2_3_3  (L:=-265.735455f, I0:=0);
INTERN R   Rpar_2_3_3  N1:=N2_3_3, N2:=N2_3_4  (R:=-90.156696m);
INTERN L   Lpar_2_3_3  N1:=N2_3_3, N2:=N2_3_4  (L:=-24.699939p, I0:=0);
INTERN R   Rpar_2_3_4  N1:=N2_3_4, N2:=N2_3_5  (R:=349.691020);
INTERN L   Lpar_2_3_4  N1:=N2_3_4, N2:=N2_3_5  (L:=88.956024n, I0:=0);
INTERN R   Rpar_2_3_5  N1:=N2_3_5, N2:=N2_3_6  (R:=308.026403m);
INTERN L   Lpar_2_3_5  N1:=N2_3_5, N2:=N2_3_6  (L:=1.159418n, I0:=0);
INTERN R   Rpar_2_3_6  N1:=N2_3_6, N2:=N2_3_7  (R:=4.021170);
INTERN L   Lpar_2_3_6  N1:=N2_3_6, N2:=N2_3_7  (L:=21.489881n, I0:=0);
INTERN R   Rpar_2_3_7  N1:=N2_3_7, N2:=N2_3_8  (R:=86.706541m);
INTERN L   Lpar_2_3_7  N1:=N2_3_7, N2:=N2_3_8  (L:=644.063210p, I0:=0);
INTERN R   Rpar_2_3_8  N1:=N2_3_8, N2:=N2_3_9  (R:=18.599185m);
INTERN L   Lpar_2_3_8  N1:=N2_3_8, N2:=N2_3_9  (L:=25.828288p, I0:=0);
INTERN R   Rpar_2_3_9  N1:=N2_3_9, N2:=GND  (R:=252.443983m);
INTERN L   Lpar_2_3_9  N1:=N2_3_9, N2:=GND  (L:=6.687979n, I0:=0);

// --- Mutual impedance Z2_4 --- 

INTERN I   IIsens_2_4  N1:=GND, N2:=z_2_4  (IS:=WMsens4.I, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=WMsens4.I);
INTERN VM  VMZ_2_4  N1:=z_2_4, N2:=GND  ();
INTERN E   EUdrop_2_4  N1:=N2_5, N2:=N2_4  (EMF:=VMZ_2_4.V, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=VMZ_2_4.V);
INTERN R   Rser_2_4_0  N1:=z_2_4, N2:=N2_4_0  (R:=-16.517133u);
INTERN L   Lser_2_4_0  N1:=N2_4_0, N2:=N2_4_1  (L:=701.038414n, I0:=0);
INTERN R   Rpar_2_4_1  N1:=N2_4_1, N2:=N2_4_2  (R:=-118.487930u);
INTERN L   Lpar_2_4_1  N1:=N2_4_1, N2:=N2_4_2  (L:=-18.015224p, I0:=0);
INTERN R   Rpar_2_4_2  N1:=N2_4_2, N2:=N2_4_3  (R:=-19.449153u);
INTERN L   Lpar_2_4_2  N1:=N2_4_2, N2:=N2_4_3  (L:=-87.833150f, I0:=0);
INTERN R   Rpar_2_4_3  N1:=N2_4_3, N2:=N2_4_4  (R:=-80.384541m);
INTERN L   Lpar_2_4_3  N1:=N2_4_3, N2:=N2_4_4  (L:=-5.669419n, I0:=0);
INTERN R   Rpar_2_4_4  N1:=N2_4_4, N2:=N2_4_5  (R:=349.691020);
INTERN L   Lpar_2_4_4  N1:=N2_4_4, N2:=N2_4_5  (L:=88.956024n, I0:=0);
INTERN R   Rpar_2_4_5  N1:=N2_4_5, N2:=N2_4_6  (R:=308.026403m);
INTERN L   Lpar_2_4_5  N1:=N2_4_5, N2:=N2_4_6  (L:=1.159418n, I0:=0);
INTERN R   Rpar_2_4_6  N1:=N2_4_6, N2:=N2_4_7  (R:=4.021170);
INTERN L   Lpar_2_4_6  N1:=N2_4_6, N2:=N2_4_7  (L:=21.489881n, I0:=0);
INTERN R   Rpar_2_4_7  N1:=N2_4_7, N2:=N2_4_8  (R:=18.397044m);
INTERN L   Lpar_2_4_7  N1:=N2_4_7, N2:=N2_4_8  (L:=733.817601p, I0:=0);
INTERN R   Rpar_2_4_8  N1:=N2_4_8, N2:=N2_4_9  (R:=1.769020);
INTERN L   Lpar_2_4_8  N1:=N2_4_8, N2:=N2_4_9  (L:=6.710325n, I0:=0);
INTERN R   Rpar_2_4_9  N1:=N2_4_9, N2:=GND  (R:=1.146634);
INTERN L   Lpar_2_4_9  N1:=N2_4_9, N2:=GND  (L:=12.556241n, I0:=0);

// --- Mutual impedance Z3_1 --- 

INTERN I   IIsens_3_1  N1:=GND, N2:=z_3_1  (IS:=WMsens1.I, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=WMsens1.I);
INTERN VM  VMZ_3_1  N1:=z_3_1, N2:=GND  ();
INTERN E   EUdrop_3_1  N1:=N3_2, N2:=N3_1  (EMF:=VMZ_3_1.V, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=VMZ_3_1.V);
INTERN R   Rser_3_1_0  N1:=z_3_1, N2:=N3_1_0  (R:=-212.495611u);
INTERN L   Lser_3_1_0  N1:=N3_1_0, N2:=N3_1_1  (L:=2.595732u, I0:=0);
INTERN R   Rpar_3_1_1  N1:=N3_1_1, N2:=N3_1_2  (R:=-331.448223m);
INTERN L   Lpar_3_1_1  N1:=N3_1_1, N2:=N3_1_2  (L:=-20.291063n, I0:=0);
INTERN R   Rpar_3_1_2  N1:=N3_1_2, N2:=N3_1_3  (R:=-12.996233m);
INTERN L   Lpar_3_1_2  N1:=N3_1_2, N2:=N3_1_3  (L:=-284.119241p, I0:=0);
INTERN R   Rpar_3_1_3  N1:=N3_1_3, N2:=N3_1_4  (R:=-62.804764m);
INTERN L   Lpar_3_1_3  N1:=N3_1_3, N2:=N3_1_4  (L:=-5.091500n, I0:=0);
INTERN R   Rpar_3_1_4  N1:=N3_1_4, N2:=N3_1_5  (R:=115.190196m);
INTERN L   Lpar_3_1_4  N1:=N3_1_4, N2:=N3_1_5  (L:=4.072112n, I0:=0);
INTERN R   Rpar_3_1_5  N1:=N3_1_5, N2:=N3_1_6  (R:=1.880159);
INTERN L   Lpar_3_1_5  N1:=N3_1_5, N2:=N3_1_6  (L:=1.667637n, I0:=0);
INTERN R   Rpar_3_1_6  N1:=N3_1_6, N2:=N3_1_7  (R:=2.480878);
INTERN L   Lpar_3_1_6  N1:=N3_1_6, N2:=N3_1_7  (L:=9.779920n, I0:=0);
INTERN R   Rpar_3_1_7  N1:=N3_1_7, N2:=N3_1_8  (R:=606.945790m);
INTERN L   Lpar_3_1_7  N1:=N3_1_7, N2:=N3_1_8  (L:=4.508442n, I0:=0);
INTERN R   Rpar_3_1_8  N1:=N3_1_8, N2:=N3_1_9  (R:=130.194294m);
INTERN L   Lpar_3_1_8  N1:=N3_1_8, N2:=N3_1_9  (L:=180.798014p, I0:=0);
INTERN R   Rpar_3_1_9  N1:=N3_1_9, N2:=GND  (R:=1.767108);
INTERN L   Lpar_3_1_9  N1:=N3_1_9, N2:=GND  (L:=46.815855n, I0:=0);

// --- Mutual impedance Z3_2 --- 

INTERN I   IIsens_3_2  N1:=GND, N2:=z_3_2  (IS:=WMsens2.I, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=WMsens2.I);
INTERN VM  VMZ_3_2  N1:=z_3_2, N2:=GND  ();
INTERN E   EUdrop_3_2  N1:=N3_3, N2:=N3_2  (EMF:=VMZ_3_2.V, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=VMZ_3_2.V);
INTERN R   Rser_3_2_0  N1:=z_3_2, N2:=N3_2_0  (R:=41.868241u);
INTERN L   Lser_3_2_0  N1:=N3_2_0, N2:=N3_2_1  (L:=756.654909n, I0:=0);
INTERN R   Rpar_3_2_1  N1:=N3_2_1, N2:=N3_2_2  (R:=-23.101861m);
INTERN L   Lpar_3_2_1  N1:=N3_2_1, N2:=N3_2_2  (L:=-4.037983n, I0:=0);
INTERN R   Rpar_3_2_2  N1:=N3_2_2, N2:=N3_2_3  (R:=-57.765884u);
INTERN L   Lpar_3_2_2  N1:=N3_2_2, N2:=N3_2_3  (L:=-265.735455f, I0:=0);
INTERN R   Rpar_3_2_3  N1:=N3_2_3, N2:=N3_2_4  (R:=-90.156696m);
INTERN L   Lpar_3_2_3  N1:=N3_2_3, N2:=N3_2_4  (L:=-24.699939p, I0:=0);
INTERN R   Rpar_3_2_4  N1:=N3_2_4, N2:=N3_2_5  (R:=349.691020);
INTERN L   Lpar_3_2_4  N1:=N3_2_4, N2:=N3_2_5  (L:=88.956024n, I0:=0);
INTERN R   Rpar_3_2_5  N1:=N3_2_5, N2:=N3_2_6  (R:=308.026403m);
INTERN L   Lpar_3_2_5  N1:=N3_2_5, N2:=N3_2_6  (L:=1.159418n, I0:=0);
INTERN R   Rpar_3_2_6  N1:=N3_2_6, N2:=N3_2_7  (R:=4.021170);
INTERN L   Lpar_3_2_6  N1:=N3_2_6, N2:=N3_2_7  (L:=21.489881n, I0:=0);
INTERN R   Rpar_3_2_7  N1:=N3_2_7, N2:=N3_2_8  (R:=86.706541m);
INTERN L   Lpar_3_2_7  N1:=N3_2_7, N2:=N3_2_8  (L:=644.063210p, I0:=0);
INTERN R   Rpar_3_2_8  N1:=N3_2_8, N2:=N3_2_9  (R:=18.599185m);
INTERN L   Lpar_3_2_8  N1:=N3_2_8, N2:=N3_2_9  (L:=25.828288p, I0:=0);
INTERN R   Rpar_3_2_9  N1:=N3_2_9, N2:=GND  (R:=252.443983m);
INTERN L   Lpar_3_2_9  N1:=N3_2_9, N2:=GND  (L:=6.687979n, I0:=0);

// --- Self impedance Z3_3 ---

INTERN R   Rser_3_3_0  N1:=N3_3, N2:=N3_3_0  (R:=1.845286m);
INTERN L   Lser_3_3_0  N1:=N3_3_0, N2:=N3_3_1  (L:=919.761189n, I0:=0);
INTERN R   Rpar_3_3_1  N1:=N3_3_1, N2:=N3_3_2  (R:=173.413083m);
INTERN L   Lpar_3_3_1  N1:=N3_3_1, N2:=N3_3_2  (L:=1.288126n, I0:=0);
INTERN R   Rpar_3_3_2  N1:=N3_3_2, N2:=N3_3_3  (R:=37.198370m);
INTERN L   Lpar_3_3_2  N1:=N3_3_2, N2:=N3_3_3  (L:=51.656575p, I0:=0);
INTERN R   Rpar_3_3_3  N1:=N3_3_3, N2:=N3_4  (R:=504.887965m);
INTERN L   Lpar_3_3_3  N1:=N3_3_3, N2:=N3_4  (L:=13.375958n, I0:=0);

// --- Mutual impedance Z3_4 --- 

INTERN I   IIsens_3_4  N1:=GND, N2:=z_3_4  (IS:=WMsens4.I, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=WMsens4.I);
INTERN VM  VMZ_3_4  N1:=z_3_4, N2:=GND  ();
INTERN E   EUdrop_3_4  N1:=N3_5, N2:=N3_4  (EMF:=VMZ_3_4.V, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=VMZ_3_4.V);
INTERN R   Rser_3_4_0  N1:=z_3_4, N2:=N3_4_0  (R:=70.828437u);
INTERN L   Lser_3_4_0  N1:=N3_4_0, N2:=N3_4_1  (L:=870.396096n, I0:=0);
INTERN R   Rpar_3_4_1  N1:=N3_4_1, N2:=N3_4_2  (R:=-7.043956m);
INTERN L   Lpar_3_4_1  N1:=N3_4_1, N2:=N3_4_2  (L:=-1.094578n, I0:=0);
INTERN R   Rpar_3_4_2  N1:=N3_4_2, N2:=N3_4_3  (R:=-1.138637m);
INTERN L   Lpar_3_4_2  N1:=N3_4_2, N2:=N3_4_3  (L:=-93.189990f, I0:=0);
INTERN R   Rpar_3_4_3  N1:=N3_4_3, N2:=N3_4_4  (R:=-43.109570m);
INTERN L   Lpar_3_4_3  N1:=N3_4_3, N2:=N3_4_4  (L:=-4.085554n, I0:=0);
INTERN R   Rpar_3_4_4  N1:=N3_4_4, N2:=N3_4_5  (R:=86.706541m);
INTERN L   Lpar_3_4_4  N1:=N3_4_4, N2:=N3_4_5  (L:=644.063210p, I0:=0);
INTERN R   Rpar_3_4_5  N1:=N3_4_5, N2:=N3_4_6  (R:=18.599185m);
INTERN L   Lpar_3_4_5  N1:=N3_4_5, N2:=N3_4_6  (L:=25.828288p, I0:=0);
INTERN R   Rpar_3_4_6  N1:=N3_4_6, N2:=N3_4_7  (R:=252.443983m);
INTERN L   Lpar_3_4_6  N1:=N3_4_6, N2:=N3_4_7  (L:=6.687979n, I0:=0);
INTERN R   Rpar_3_4_7  N1:=N3_4_7, N2:=N3_4_8  (R:=18.397044m);
INTERN L   Lpar_3_4_7  N1:=N3_4_7, N2:=N3_4_8  (L:=733.817601p, I0:=0);
INTERN R   Rpar_3_4_8  N1:=N3_4_8, N2:=N3_4_9  (R:=1.769020);
INTERN L   Lpar_3_4_8  N1:=N3_4_8, N2:=N3_4_9  (L:=6.710325n, I0:=0);
INTERN R   Rpar_3_4_9  N1:=N3_4_9, N2:=GND  (R:=1.146634);
INTERN L   Lpar_3_4_9  N1:=N3_4_9, N2:=GND  (L:=12.556241n, I0:=0);

// --- Mutual impedance Z4_1 --- 

INTERN I   IIsens_4_1  N1:=GND, N2:=z_4_1  (IS:=WMsens1.I, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=WMsens1.I);
INTERN VM  VMZ_4_1  N1:=z_4_1, N2:=GND  ();
INTERN E   EUdrop_4_1  N1:=N4_2, N2:=N4_1  (EMF:=VMZ_4_1.V, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=VMZ_4_1.V);
INTERN R   Rser_4_1_0  N1:=z_4_1, N2:=N4_1_0  (R:=658.998715u);
INTERN L   Lser_4_1_0  N1:=N4_1_0, N2:=N4_1_1  (L:=2.534001u, I0:=0);
INTERN R   Rpar_4_1_1  N1:=N4_1_1, N2:=N4_1_2  (R:=-5.794223m);
INTERN L   Lpar_4_1_1  N1:=N4_1_1, N2:=N4_1_2  (L:=-65.247742p, I0:=0);
INTERN R   Rpar_4_1_2  N1:=N4_1_2, N2:=N4_1_3  (R:=-110.826770m);
INTERN L   Lpar_4_1_2  N1:=N4_1_2, N2:=N4_1_3  (L:=-19.280251n, I0:=0);
INTERN R   Rpar_4_1_3  N1:=N4_1_3, N2:=N4_1_4  (R:=-2.470226m);
INTERN L   Lpar_4_1_3  N1:=N4_1_3, N2:=N4_1_4  (L:=-1.072309p, I0:=0);
INTERN R   Rpar_4_1_4  N1:=N4_1_4, N2:=N4_1_5  (R:=115.190196m);
INTERN L   Lpar_4_1_4  N1:=N4_1_4, N2:=N4_1_5  (L:=4.072112n, I0:=0);
INTERN R   Rpar_4_1_5  N1:=N4_1_5, N2:=N4_1_6  (R:=1.880159);
INTERN L   Lpar_4_1_5  N1:=N4_1_5, N2:=N4_1_6  (L:=1.667637n, I0:=0);
INTERN R   Rpar_4_1_6  N1:=N4_1_6, N2:=N4_1_7  (R:=2.480878);
INTERN L   Lpar_4_1_6  N1:=N4_1_6, N2:=N4_1_7  (L:=9.779920n, I0:=0);
INTERN R   Rpar_4_1_7  N1:=N4_1_7, N2:=N4_1_8  (R:=128.779306m);
INTERN L   Lpar_4_1_7  N1:=N4_1_7, N2:=N4_1_8  (L:=5.136723n, I0:=0);
INTERN R   Rpar_4_1_8  N1:=N4_1_8, N2:=N4_1_9  (R:=12.383141);
INTERN L   Lpar_4_1_8  N1:=N4_1_8, N2:=N4_1_9  (L:=46.972273n, I0:=0);
INTERN R   Rpar_4_1_9  N1:=N4_1_9, N2:=GND  (R:=8.026437);
INTERN L   Lpar_4_1_9  N1:=N4_1_9, N2:=GND  (L:=87.893690n, I0:=0);

// --- Mutual impedance Z4_2 --- 

INTERN I   IIsens_4_2  N1:=GND, N2:=z_4_2  (IS:=WMsens2.I, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=WMsens2.I);
INTERN VM  VMZ_4_2  N1:=z_4_2, N2:=GND  ();
INTERN E   EUdrop_4_2  N1:=N4_3, N2:=N4_2  (EMF:=VMZ_4_2.V, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=VMZ_4_2.V);
INTERN R   Rser_4_2_0  N1:=z_4_2, N2:=N4_2_0  (R:=-16.517133u);
INTERN L   Lser_4_2_0  N1:=N4_2_0, N2:=N4_2_1  (L:=701.038414n, I0:=0);
INTERN R   Rpar_4_2_1  N1:=N4_2_1, N2:=N4_2_2  (R:=-118.487930u);
INTERN L   Lpar_4_2_1  N1:=N4_2_1, N2:=N4_2_2  (L:=-18.015224p, I0:=0);
INTERN R   Rpar_4_2_2  N1:=N4_2_2, N2:=N4_2_3  (R:=-19.449153u);
INTERN L   Lpar_4_2_2  N1:=N4_2_2, N2:=N4_2_3  (L:=-87.833150f, I0:=0);
INTERN R   Rpar_4_2_3  N1:=N4_2_3, N2:=N4_2_4  (R:=-80.384541m);
INTERN L   Lpar_4_2_3  N1:=N4_2_3, N2:=N4_2_4  (L:=-5.669419n, I0:=0);
INTERN R   Rpar_4_2_4  N1:=N4_2_4, N2:=N4_2_5  (R:=349.691020);
INTERN L   Lpar_4_2_4  N1:=N4_2_4, N2:=N4_2_5  (L:=88.956024n, I0:=0);
INTERN R   Rpar_4_2_5  N1:=N4_2_5, N2:=N4_2_6  (R:=308.026403m);
INTERN L   Lpar_4_2_5  N1:=N4_2_5, N2:=N4_2_6  (L:=1.159418n, I0:=0);
INTERN R   Rpar_4_2_6  N1:=N4_2_6, N2:=N4_2_7  (R:=4.021170);
INTERN L   Lpar_4_2_6  N1:=N4_2_6, N2:=N4_2_7  (L:=21.489881n, I0:=0);
INTERN R   Rpar_4_2_7  N1:=N4_2_7, N2:=N4_2_8  (R:=18.397044m);
INTERN L   Lpar_4_2_7  N1:=N4_2_7, N2:=N4_2_8  (L:=733.817601p, I0:=0);
INTERN R   Rpar_4_2_8  N1:=N4_2_8, N2:=N4_2_9  (R:=1.769020);
INTERN L   Lpar_4_2_8  N1:=N4_2_8, N2:=N4_2_9  (L:=6.710325n, I0:=0);
INTERN R   Rpar_4_2_9  N1:=N4_2_9, N2:=GND  (R:=1.146634);
INTERN L   Lpar_4_2_9  N1:=N4_2_9, N2:=GND  (L:=12.556241n, I0:=0);

// --- Mutual impedance Z4_3 --- 

INTERN I   IIsens_4_3  N1:=GND, N2:=z_4_3  (IS:=WMsens3.I, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=WMsens3.I);
INTERN VM  VMZ_4_3  N1:=z_4_3, N2:=GND  ();
INTERN E   EUdrop_4_3  N1:=N4_4, N2:=N4_3  (EMF:=VMZ_4_3.V, PARTDERIV:=1, AC_PHASE:=0, AC_MAG:=VMZ_4_3.V);
INTERN R   Rser_4_3_0  N1:=z_4_3, N2:=N4_3_0  (R:=70.828437u);
INTERN L   Lser_4_3_0  N1:=N4_3_0, N2:=N4_3_1  (L:=870.396096n, I0:=0);
INTERN R   Rpar_4_3_1  N1:=N4_3_1, N2:=N4_3_2  (R:=-7.043956m);
INTERN L   Lpar_4_3_1  N1:=N4_3_1, N2:=N4_3_2  (L:=-1.094578n, I0:=0);
INTERN R   Rpar_4_3_2  N1:=N4_3_2, N2:=N4_3_3  (R:=-1.138637m);
INTERN L   Lpar_4_3_2  N1:=N4_3_2, N2:=N4_3_3  (L:=-93.189990f, I0:=0);
INTERN R   Rpar_4_3_3  N1:=N4_3_3, N2:=N4_3_4  (R:=-43.109570m);
INTERN L   Lpar_4_3_3  N1:=N4_3_3, N2:=N4_3_4  (L:=-4.085554n, I0:=0);
INTERN R   Rpar_4_3_4  N1:=N4_3_4, N2:=N4_3_5  (R:=86.706541m);
INTERN L   Lpar_4_3_4  N1:=N4_3_4, N2:=N4_3_5  (L:=644.063210p, I0:=0);
INTERN R   Rpar_4_3_5  N1:=N4_3_5, N2:=N4_3_6  (R:=18.599185m);
INTERN L   Lpar_4_3_5  N1:=N4_3_5, N2:=N4_3_6  (L:=25.828288p, I0:=0);
INTERN R   Rpar_4_3_6  N1:=N4_3_6, N2:=N4_3_7  (R:=252.443983m);
INTERN L   Lpar_4_3_6  N1:=N4_3_6, N2:=N4_3_7  (L:=6.687979n, I0:=0);
INTERN R   Rpar_4_3_7  N1:=N4_3_7, N2:=N4_3_8  (R:=18.397044m);
INTERN L   Lpar_4_3_7  N1:=N4_3_7, N2:=N4_3_8  (L:=733.817601p, I0:=0);
INTERN R   Rpar_4_3_8  N1:=N4_3_8, N2:=N4_3_9  (R:=1.769020);
INTERN L   Lpar_4_3_8  N1:=N4_3_8, N2:=N4_3_9  (L:=6.710325n, I0:=0);
INTERN R   Rpar_4_3_9  N1:=N4_3_9, N2:=GND  (R:=1.146634);
INTERN L   Lpar_4_3_9  N1:=N4_3_9, N2:=GND  (L:=12.556241n, I0:=0);

// --- Self impedance Z4_4 ---

INTERN R   Rser_4_4_0  N1:=N4_4, N2:=N4_4_0  (R:=2.331626m);
INTERN L   Lser_4_4_0  N1:=N4_4_0, N2:=N4_4_1  (L:=951.565645n, I0:=0);
INTERN R   Rpar_4_4_1  N1:=N4_4_1, N2:=N4_4_2  (R:=36.794087m);
INTERN L   Lpar_4_4_1  N1:=N4_4_1, N2:=N4_4_2  (L:=1.467635n, I0:=0);
INTERN R   Rpar_4_4_2  N1:=N4_4_2, N2:=N4_4_3  (R:=3.538040);
INTERN L   Lpar_4_4_2  N1:=N4_4_2, N2:=N4_4_3  (L:=13.420649n, I0:=0);
INTERN R   Rpar_4_4_3  N1:=N4_4_3, N2:=N4_5  (R:=2.293268);
INTERN L   Lpar_4_4_3  N1:=N4_4_3, N2:=N4_5  (L:=25.112483n, I0:=0);

// --- Losses Distribution of Magnetic Component ---

INTERN EQU {TotalLosses:=WMsens1.P+WMsens2.P+WMsens3.P+WMsens4.P;} DST: SIM(Type:=SSGM, Sequ:=PRE);
UMODEL MOV_AV AvgTotalLosses (INPUT:=TotalLosses, TSTART:=0, TSTOP:=Tend, PERIOD:=Period) SRC: DB(Lib:="Simplorer Elements\Basic Elements\Basic Elements");

INTERN EQU {CoreLosses:=WMsensCore1.P+WMsensCore2.P+WMsensCore3.P+WMsensCore4.P;} DST: SIM(Type:=SSGM, Sequ:=PRE);
UMODEL MOV_AV AvgCoreLosses (INPUT:=CoreLosses, TSTART:=0, TSTOP:=Tend, PERIOD:=Period) SRC: DB(Lib:="Simplorer Elements\Basic Elements\Basic Elements");

INTERN EQU {WireLosses:=TotalLosses-CoreLosses;} DST: SIM(Type:=SSGM, Sequ:=PRE);
INTERN EQU {AvgWireLosses:=AvgTotalLosses.MEAN-AvgCoreLosses.MEAN;} DST: SIM(Type:=SSGM, Sequ:=PRE);
}
